
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: tiegom2/notifications
        name: notifications
        env:
          - name: TCP_PORT
            value: '3000'
          - name: GOOGLE_OAUTH_CLIENT_ID
            value: 474561109502-Abcaz3pvg9th7bvt776q2j5jvvdae8ni.apps.googleusercontent.com
          - name: GOOGLE_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google
                key: clientSecret
          - name: GOOGLE_OAUTH_REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: google
                key: refreshToken
          - name: SMTP_USER
            value: hosthaven@gmail.com
        ports:
          - containerPort: 3000

